// Client-side ballot derivation — the second algorithm source of truth (M23).
//
// In templates D/E/F/G the submitted ballot's `irv`/`approval` fields are
// derived from STAR scores, manual tie-break orders, and approval cutoffs
// rather than entered directly. That logic originally lived only in Flutter's
// `lib/presentation/screens/ballot_screen.dart`; this is its runtime-agnostic
// TypeScript reimplementation, locked against the Dart original by the
// cross-language fixtures in `fixtures/derivation/` (generated by
// `tool/derive_fixtures.dart`). Both stacks must derive identical payloads.
//
// No Deno/network imports — importable from any TS runtime. M10 (the React
// ballot port) consumes this instead of re-deriving in components. When M5
// scaffolds the React app this module may be re-homed into a shared package;
// keep it dependency-free so that move is trivial.
//
// Ordering semantics mirror the Dart source exactly (no incidental sorting):
// tie-break order with missing members appended in candidate order, score-0
// candidates last, approval lists in candidate/ranking order.

export type Scores = Record<string, number>;
// Keyed by score; at runtime (and in JSON) the keys are strings.
export type TieBreaks = Record<string, string[]>;

export interface DerivationState {
  scores?: Scores;
  rankings?: string[];
  approvals?: string[];
  tieBreaks?: TieBreaks;
  approvalCutoff?: number;
  approvalTopK?: number;
  fptpChoice?: string | null;
}

export interface Payload {
  star?: Scores;
  irv?: string[];
  approval?: string[];
  fptp?: string;
}

function clamp(value: number, lower: number, upper: number): number {
  return Math.min(Math.max(value, lower), upper);
}

/// Score desc → within a tie group, stored tie-break order (filtered to the
/// group, missing members appended in candidate order) → else candidate order.
export function deriveRanking(
  scores: Scores,
  tieBreaks: TieBreaks,
  candidateIds: string[],
): string[] {
  const byScore: Record<number, string[]> = {};
  for (const id of candidateIds) {
    const score = scores[id] ?? 0;
    (byScore[score] ??= []).push(id);
  }

  const result: string[] = [];
  const sortedScores = Object.keys(byScore).map(Number).sort((a, b) => b - a);

  for (const score of sortedScores) {
    const group = byScore[score];
    if (group.length === 1) {
      result.push(group[0]);
    } else if (tieBreaks[score] !== undefined) {
      const tieOrder = tieBreaks[score];
      for (const id of tieOrder) if (group.includes(id)) result.push(id);
      for (const id of group) if (!tieOrder.includes(id)) result.push(id);
    } else {
      for (const id of candidateIds) if (group.includes(id)) result.push(id);
    }
  }
  return result;
}

/// Approve candidates with score >= cutoff, in candidate order.
export function deriveApprovalsFromScores(
  scores: Scores,
  candidateIds: string[],
  cutoff: number,
): string[] {
  return candidateIds.filter((id) => (scores[id] ?? 0) >= cutoff);
}

/// Approve the first topK entries of the ranking.
export function deriveApprovalsFromRanking(
  ranking: string[],
  topK: number,
): string[] {
  if (topK <= 0) return [];
  return ranking.slice(0, topK);
}

/// Score>0 tie groups (2+ members), keyed by score.
function getUiTiedGroups(
  scores: Scores,
  candidateIds: string[],
): TieBreaks {
  const byScore: TieBreaks = {};
  for (const id of candidateIds) {
    const score = scores[id] ?? 0;
    if (score === 0) continue;
    (byScore[score] ??= []).push(id);
  }
  const out: TieBreaks = {};
  for (const [score, group] of Object.entries(byScore)) {
    if (group.length > 1) out[score] = group;
  }
  return out;
}

/// Maintain tie groups after a score change: preserve existing order, append
/// newly-tied members, drop departed ones, and remove groups no longer tied.
export function syncTieBreaks(
  tieBreaksIn: TieBreaks,
  scores: Scores,
  candidateIds: string[],
): TieBreaks {
  const tieBreaks: TieBreaks = {};
  for (const [score, order] of Object.entries(tieBreaksIn)) {
    tieBreaks[score] = [...order];
  }
  const groups = getUiTiedGroups(scores, candidateIds);

  for (const [score, group] of Object.entries(groups)) {
    if (tieBreaks[score] === undefined) {
      tieBreaks[score] = [...group];
    } else {
      const current = tieBreaks[score];
      for (const id of group) if (!current.includes(id)) current.push(id);
      for (let i = current.length - 1; i >= 0; i--) {
        if (!group.includes(current[i])) current.splice(i, 1);
      }
    }
  }

  for (const score of Object.keys(tieBreaks)) {
    if (groups[score] === undefined) delete tieBreaks[score];
  }
  return tieBreaks;
}

/// Rebuild tie groups from an explicit display order, grouping by score
/// (INCLUDING score 0) and keeping groups with 2+ members in list order.
export function rebuildTieBreaksFromOrder(
  order: string[],
  scores: Scores,
): TieBreaks {
  const byScore: TieBreaks = {};
  for (const id of order) {
    const score = scores[id] ?? 0;
    (byScore[score] ??= []).push(id);
  }
  const tieBreaks: TieBreaks = {};
  for (const [score, group] of Object.entries(byScore)) {
    if (group.length > 1) tieBreaks[score] = group;
  }
  return tieBreaks;
}

/// The #83 (rank-first-score-later auto-bump) and #78 (0-score reorder) drag
/// transition. Pure: takes/returns state, no UI. `newIndexRaw` is the raw
/// ReorderableListView index (adjusted by -1 when dragging downward, matching
/// Flutter). Returns the updated scores, rebuilt tie-breaks, and new order.
export function applyReorder(
  scoresIn: Scores,
  displayOrder: string[],
  oldIndex: number,
  newIndexRaw: number,
): { scores: Scores; tieBreaks: TieBreaks; order: string[] } {
  const scores: Scores = { ...scoresIn };
  let newIndex = newIndexRaw;
  if (newIndex > oldIndex) newIndex--;
  const reordered = [...displayOrder];
  const [draggedId] = reordered.splice(oldIndex, 1);
  reordered.splice(newIndex, 0, draggedId);

  const currentScore = scores[draggedId] ?? 0;
  const aboveIds = reordered.slice(0, newIndex);
  const hasZeroAbove = aboveIds.some((id) => (scores[id] ?? 0) === 0);

  if (currentScore === 0 && !hasZeroAbove) {
    const newScore = aboveIds.length === 0
      ? 5
      : clamp(Math.min(...aboveIds.map((id) => scores[id] ?? 0)) - 1, 0, 5);
    scores[draggedId] = newScore;
  } else {
    const aboveScore = newIndex > 0
      ? (scores[reordered[newIndex - 1]] ?? 0)
      : 5;
    const belowScore = newIndex < reordered.length - 1
      ? (scores[reordered[newIndex + 1]] ?? 0)
      : 0;
    scores[draggedId] = clamp(currentScore, belowScore, aboveScore);
  }

  const tieBreaks = rebuildTieBreaksFromOrder(reordered, scores);
  return { scores, tieBreaks, order: reordered };
}

/// Candidates at the (nonzero) maximum score; empty when the max is 0.
function getTopScoredCandidates(
  scores: Scores,
  candidateIds: string[],
): string[] {
  let maxScore = 0;
  for (const id of candidateIds) {
    const s = scores[id] ?? 0;
    if (s > maxScore) maxScore = s;
  }
  if (maxScore === 0) return [];
  return candidateIds.filter((id) => (scores[id] ?? 0) === maxScore);
}

/// Auto-select a single top scorer; clear the current choice when it drops out
/// of the top set; otherwise preserve it.
export function autoFptpFromScores(
  scores: Scores,
  candidateIds: string[],
  currentChoice: string | null,
): string | null {
  const top = getTopScoredCandidates(scores, candidateIds);
  if (top.length === 1) {
    return top[0];
  } else if (currentChoice !== null && !top.includes(currentChoice)) {
    return null;
  }
  return currentChoice;
}

/// Per-template payload assembly (A–G) + trailing fptp when enabled and chosen.
/// Templates A/D use the direct `rankings`; F/G derive the ranking from scores.
export function buildPayload(
  template: string,
  state: DerivationState,
  candidateIds: string[],
  includeFptp: boolean,
): Payload {
  const scores = state.scores ?? {};
  const rankings = state.rankings ?? [];
  const approvals = state.approvals ?? [];
  const tieBreaks = state.tieBreaks ?? {};
  const cutoff = state.approvalCutoff ?? 3;
  const topK = state.approvalTopK ?? 0;
  const fptpChoice = state.fptpChoice ?? null;

  const payload: Payload = {};
  switch (template) {
    case "A":
      payload.irv = [...rankings];
      break;
    case "B":
      payload.star = { ...scores };
      break;
    case "C":
      payload.approval = [...approvals];
      break;
    case "D":
      payload.irv = [...rankings];
      payload.approval = deriveApprovalsFromRanking(rankings, topK);
      break;
    case "E":
      payload.star = { ...scores };
      payload.approval = deriveApprovalsFromScores(
        scores,
        candidateIds,
        cutoff,
      );
      break;
    case "F":
      payload.star = { ...scores };
      payload.irv = deriveRanking(scores, tieBreaks, candidateIds);
      break;
    case "G": {
      const ranking = deriveRanking(scores, tieBreaks, candidateIds);
      payload.star = { ...scores };
      payload.irv = ranking;
      payload.approval = deriveApprovalsFromRanking(ranking, topK);
      break;
    }
  }
  if (includeFptp && fptpChoice !== null) {
    payload.fptp = fptpChoice;
  }
  return payload;
}
